# Generated by Django 4.0.10 on 2026-09-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_rename_employee_employee_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(choices=[('X', 'Present'), ('SL', 'Sick Leave'), ('L', 'Leave'), ('NA', 'Not Available'), ('WFH', 'Work From Home'), ('CL', 'Casual Leave'), ('0.5SL', 'Half day Sick Leave'), ('0.5CL', 'Half day Casual Leave')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
