# Generated by Django 4.0.10 on 2026-09-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_rename_employee_employee_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.DateField(max_length=10)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('X', 'Present'), ('SL', 'Sick Leave'), ('L', 'Leave'), ('NA', 'Not Available'), ('WFH', 'Work From Home'), ('CL', 'Casual Leave'), ('0.5SL', 'Half day Sick Leave'), ('0.5CL', 'Half day Casual Leave')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
