# Generated by Django 4.0.10 on 2026-09-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
