# Generated by Django 4.0.10 on 2026-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('employee', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
