# Generated by Django 4.0.10 on 2026-09-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='employee_name',
        ),
    ]
