# Generated by Django 4.0.10 on 2026-09-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employee_employee_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('INTERN', 'Intern')], default='EMPLOYEE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_employees', to='employees.employee'),
        ),
    ]
