# Generated by Django 4.0.10 on 2026-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
