# Generated by Django 4.0.10 on 2026-09-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_location_alter_employee_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
