# Generated by Django 4.0.10 on 2026-09-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_reportingmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.reportingmanager'),
        ),
    ]
